on:
  push:

name: build based on commit
jobs:
  generate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: support ape bins and SSL things
        run: bash ./.github/scripts/setup
      - name: build Cosmo (minimal)
        working-directory: /ahgamut/superconfigure
        run: bash ./.github/scripts/pr-cosmo
      - name: build updates from commit
        working-directory: /ahgamut/superconfigure
        env:
          COLLECTION: no
        run: bash ./.github/scripts/pr-build
      - name: collect into zip
        working-directory: /ahgamut/superconfigure
        env:
          ZFILENAME: "updates"
        run: bash ./.github/scripts/collectzip
      - name: Upload binaries as artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: "/ahgamut/superconfigure/updates-dbg.zip"
          compression-level: 0
          if-no-files-found: error
